# .circleci/config.yml
version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.9

jobs:
  test-python:
    executor: python-executor
    working_directory: ~/repo/clickup-goal-api-tests-python
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            cd clickup-goal-api-tests-python
            pip install -r requirements.txt
      - run:
          name: Run pytest
          command: |
            cd clickup-goal-api-tests-python
            pytest

  test-cypress:
    # Меняем executor: вместо node-executor указываем напрямую cypress/included:14.4.0
    docker:
      - image: cypress/included:14.4.0
    working_directory: ~/repo/clickup-goal-api-tests
    steps:
      - checkout

      - run:
          name: Install project dependencies
          command: |
            cd clickup-goal-api-tests
            npm ci

      - run:
          name: Run Cypress tests
          command: |
            cd clickup-goal-api-tests
            npx cypress run

  test-postman:
    docker:
      - image: postman/newman:alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Postman collection
          command: |
            newman run "HW 4.postman_collection.json" \
              -e "Env hw 4.postman_environment.json" \
              --insecure

workflows:
  version: 2
  test-all:
    jobs:
      - test-python
      - test-cypress
      - test-postman

