version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.1

jobs:
  test-cypress:
    executor: node-executor
    working_directory: ~/project
    environment:
      CYPRESS_clickUpToken: pk_200540127_JVDGGDGR64FUSZZJDAI0UV1C2WJ9GETA
      CYPRESS_workspaceId: 90151244709
      CYPRESS_goalFolderId: 90157352427
      CYPRESS_listId: 901511749764
      CYPRESS_baseUrl: https://api.clickup.com/api/v2
    steps:
      - checkout:
          path: ~/project
      - run: npm ci
      - run: npx cypress run --e2e
          
workflows:
  version: 2
  run-cypress:
    jobs:
      - test-cypress
